//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iec.ch/61850/2003/SCL", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;
