//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tBaseElement">
 *       &lt;sequence>
 *         &lt;element name="Header" type="{http://www.iec.ch/61850/2003/SCL}tHeader"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2003/SCL}Substation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2003/SCL}Communication" minOccurs="0"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2003/SCL}IED" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2003/SCL}DataTypeTemplates" minOccurs="0"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2003/SCL}Line" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.iec.ch/61850/2003/SCL}Process" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.iec.ch/61850/2003/SCL}tSclVersion" fixed="2007" />
 *       &lt;attribute name="revision" use="required" type="{http://www.iec.ch/61850/2003/SCL}tSclRevision" fixed="B" />
 *       &lt;attribute name="release" use="required" type="{http://www.iec.ch/61850/2003/SCL}tSclRelease" fixed="4" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "substation",
    "communication",
    "ied",
    "dataTypeTemplates",
    "line",
    "process"
})
@XmlRootElement(name = "SCL")
public class SCL
    extends TBaseElement
{

    @XmlElement(name = "Header", required = true)
    protected THeader header;
    @XmlElement(name = "Substation")
    protected List<TSubstation> substation;
    @XmlElement(name = "Communication")
    protected TCommunication communication;
    @XmlElement(name = "IED")
    protected List<TIED> ied;
    @XmlElement(name = "DataTypeTemplates")
    protected TDataTypeTemplates dataTypeTemplates;
    @XmlElement(name = "Line")
    protected List<TLine> line;
    @XmlElement(name = "Process")
    protected List<TProcess> process;
    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "revision", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String revision;
    @XmlAttribute(name = "release", required = true)
    protected short release;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link THeader }
     *     
     */
    public THeader getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link THeader }
     *     
     */
    public void setHeader(THeader value) {
        this.header = value;
    }

    /**
     * Gets the value of the substation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TSubstation }
     * 
     * 
     */
    public List<TSubstation> getSubstation() {
        if (substation == null) {
            substation = new ArrayList<TSubstation>();
        }
        return this.substation;
    }

    /**
     * Gets the value of the communication property.
     * 
     * @return
     *     possible object is
     *     {@link TCommunication }
     *     
     */
    public TCommunication getCommunication() {
        return communication;
    }

    /**
     * Sets the value of the communication property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCommunication }
     *     
     */
    public void setCommunication(TCommunication value) {
        this.communication = value;
    }

    /**
     * Gets the value of the ied property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ied property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIED().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TIED }
     * 
     * 
     */
    public List<TIED> getIED() {
        if (ied == null) {
            ied = new LinkedList<>();
        }
        return this.ied;
    }

    /**
     * Gets the value of the dataTypeTemplates property.
     * 
     * @return
     *     possible object is
     *     {@link TDataTypeTemplates }
     *     
     */
    public TDataTypeTemplates getDataTypeTemplates() {
        return dataTypeTemplates;
    }

    /**
     * Sets the value of the dataTypeTemplates property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataTypeTemplates }
     *     
     */
    public void setDataTypeTemplates(TDataTypeTemplates value) {
        this.dataTypeTemplates = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the line property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TLine }
     * 
     * 
     */
    public List<TLine> getLine() {
        if (line == null) {
            line = new ArrayList<TLine>();
        }
        return this.line;
    }

    /**
     * Gets the value of the process property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the process property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TProcess }
     * 
     * 
     */
    public List<TProcess> getProcess() {
        if (process == null) {
            process = new ArrayList<TProcess>();
        }
        return this.process;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "2007";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        if (revision == null) {
            return "B";
        } else {
            return revision;
        }
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the release property.
     * 
     */
    public short getRelease() {
        return release;
    }

    /**
     * Sets the value of the release property.
     * 
     */
    public void setRelease(short value) {
        this.release = value;
    }

}
