//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tAccessPoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAccessPoint">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tUnNaming">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="Server" type="{http://www.iec.ch/61850/2003/SCL}tServer"/>
 *           &lt;element ref="{http://www.iec.ch/61850/2003/SCL}LN" maxOccurs="unbounded"/>
 *           &lt;element name="ServerAt" type="{http://www.iec.ch/61850/2003/SCL}tServerAt"/>
 *         &lt;/choice>
 *         &lt;element name="Services" type="{http://www.iec.ch/61850/2003/SCL}tServices" minOccurs="0"/>
 *         &lt;element name="GOOSESecurity" type="{http://www.iec.ch/61850/2003/SCL}tCertificate" maxOccurs="7" minOccurs="0"/>
 *         &lt;element name="SMVSecurity" type="{http://www.iec.ch/61850/2003/SCL}tCertificate" maxOccurs="7" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.iec.ch/61850/2003/SCL}tAccessPointName" />
 *       &lt;attribute name="router" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="clock" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="kdc" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAccessPoint", propOrder = {
    "server",
    "ln",
    "serverAt",
    "services",
    "gooseSecurity",
    "smvSecurity"
})
public class TAccessPoint
    extends TUnNaming
{

    @XmlElement(name = "Server")
    protected TServer server;
    @XmlElement(name = "LN")
    protected List<TLN> ln;
    @XmlElement(name = "ServerAt")
    protected TServerAt serverAt;
    @XmlElement(name = "Services")
    protected TServices services;
    @XmlElement(name = "GOOSESecurity")
    protected List<TCertificate> gooseSecurity;
    @XmlElement(name = "SMVSecurity")
    protected List<TCertificate> smvSecurity;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "router")
    protected Boolean router;
    @XmlAttribute(name = "clock")
    protected Boolean clock;
    @XmlAttribute(name = "kdc")
    protected Boolean kdc;

    /**
     * Gets the value of the server property.
     * 
     * @return
     *     possible object is
     *     {@link TServer }
     *     
     */
    public TServer getServer() {
        return server;
    }

    /**
     * Sets the value of the server property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServer }
     *     
     */
    public void setServer(TServer value) {
        this.server = value;
    }

    /**
     * Gets the value of the ln property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ln property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TLN }
     * 
     * 
     */
    public List<TLN> getLN() {
        if (ln == null) {
            ln = new ArrayList<TLN>();
        }
        return this.ln;
    }

    /**
     * Gets the value of the serverAt property.
     * 
     * @return
     *     possible object is
     *     {@link TServerAt }
     *     
     */
    public TServerAt getServerAt() {
        return serverAt;
    }

    /**
     * Sets the value of the serverAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServerAt }
     *     
     */
    public void setServerAt(TServerAt value) {
        this.serverAt = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link TServices }
     *     
     */
    public TServices getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServices }
     *     
     */
    public void setServices(TServices value) {
        this.services = value;
    }

    /**
     * Gets the value of the gooseSecurity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gooseSecurity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGOOSESecurity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TCertificate }
     * 
     * 
     */
    public List<TCertificate> getGOOSESecurity() {
        if (gooseSecurity == null) {
            gooseSecurity = new ArrayList<TCertificate>();
        }
        return this.gooseSecurity;
    }

    /**
     * Gets the value of the smvSecurity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smvSecurity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSMVSecurity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TCertificate }
     * 
     * 
     */
    public List<TCertificate> getSMVSecurity() {
        if (smvSecurity == null) {
            smvSecurity = new ArrayList<TCertificate>();
        }
        return this.smvSecurity;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the router property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRouter() {
        if (router == null) {
            return false;
        } else {
            return router;
        }
    }

    /**
     * Sets the value of the router property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRouter(Boolean value) {
        this.router = value;
    }

    /**
     * Gets the value of the clock property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isClock() {
        if (clock == null) {
            return false;
        } else {
            return clock;
        }
    }

    /**
     * Sets the value of the clock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClock(Boolean value) {
        this.clock = value;
    }

    /**
     * Gets the value of the kdc property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isKdc() {
        if (kdc == null) {
            return false;
        } else {
            return kdc;
        }
    }

    /**
     * Sets the value of the kdc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKdc(Boolean value) {
        this.kdc = value;
    }

}
