//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tCertificate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCertificate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tNaming">
 *       &lt;sequence>
 *         &lt;element name="Subject" type="{http://www.iec.ch/61850/2003/SCL}tCert"/>
 *         &lt;element name="IssuerName" type="{http://www.iec.ch/61850/2003/SCL}tCert"/>
 *       &lt;/sequence>
 *       &lt;attribute name="xferNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="serialNumber" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *             &lt;minLength value="1"/>
 *             &lt;pattern value="[0-9]+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCertificate", propOrder = {
    "subject",
    "issuerName"
})
public class TCertificate
    extends TNaming
{

    @XmlElement(name = "Subject", required = true)
    protected TCert subject;
    @XmlElement(name = "IssuerName", required = true)
    protected TCert issuerName;
    @XmlAttribute(name = "xferNumber")
    @XmlSchemaType(name = "unsignedInt")
    protected Long xferNumber;
    @XmlAttribute(name = "serialNumber", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String serialNumber;

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link TCert }
     *     
     */
    public TCert getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCert }
     *     
     */
    public void setSubject(TCert value) {
        this.subject = value;
    }

    /**
     * Gets the value of the issuerName property.
     * 
     * @return
     *     possible object is
     *     {@link TCert }
     *     
     */
    public TCert getIssuerName() {
        return issuerName;
    }

    /**
     * Sets the value of the issuerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCert }
     *     
     */
    public void setIssuerName(TCert value) {
        this.issuerName = value;
    }

    /**
     * Gets the value of the xferNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getXferNumber() {
        return xferNumber;
    }

    /**
     * Sets the value of the xferNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setXferNumber(Long value) {
        this.xferNumber = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

}
