//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tClientServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tClientServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TimeSyncProt" type="{http://www.iec.ch/61850/2003/SCL}tTimeSyncProt" minOccurs="0"/>
 *         &lt;element name="McSecurity" type="{http://www.iec.ch/61850/2003/SCL}tMcSecurity" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="goose" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="gsse" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="bufReport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="unbufReport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="readLog" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="sv" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="supportsLdName" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="maxAttributes">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="maxReports">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="maxGOOSE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="maxSMV">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="rGOOSE" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="rSV" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="noIctBinding" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tClientServices", propOrder = {
    "timeSyncProt",
    "mcSecurity"
})
public class TClientServices {

    @XmlElement(name = "TimeSyncProt")
    protected TTimeSyncProt timeSyncProt;
    @XmlElement(name = "McSecurity")
    protected TMcSecurity mcSecurity;
    @XmlAttribute(name = "goose")
    protected Boolean goose;
    @XmlAttribute(name = "gsse")
    protected Boolean gsse;
    @XmlAttribute(name = "bufReport")
    protected Boolean bufReport;
    @XmlAttribute(name = "unbufReport")
    protected Boolean unbufReport;
    @XmlAttribute(name = "readLog")
    protected Boolean readLog;
    @XmlAttribute(name = "sv")
    protected Boolean sv;
    @XmlAttribute(name = "supportsLdName")
    protected Boolean supportsLdName;
    @XmlAttribute(name = "maxAttributes")
    protected Long maxAttributes;
    @XmlAttribute(name = "maxReports")
    protected Long maxReports;
    @XmlAttribute(name = "maxGOOSE")
    protected Long maxGOOSE;
    @XmlAttribute(name = "maxSMV")
    protected Long maxSMV;
    @XmlAttribute(name = "rGOOSE")
    protected Boolean rgoose;
    @XmlAttribute(name = "rSV")
    protected Boolean rsv;
    @XmlAttribute(name = "noIctBinding")
    protected Boolean noIctBinding;

    /**
     * Gets the value of the timeSyncProt property.
     * 
     * @return
     *     possible object is
     *     {@link TTimeSyncProt }
     *     
     */
    public TTimeSyncProt getTimeSyncProt() {
        return timeSyncProt;
    }

    /**
     * Sets the value of the timeSyncProt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTimeSyncProt }
     *     
     */
    public void setTimeSyncProt(TTimeSyncProt value) {
        this.timeSyncProt = value;
    }

    /**
     * Gets the value of the mcSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link TMcSecurity }
     *     
     */
    public TMcSecurity getMcSecurity() {
        return mcSecurity;
    }

    /**
     * Sets the value of the mcSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMcSecurity }
     *     
     */
    public void setMcSecurity(TMcSecurity value) {
        this.mcSecurity = value;
    }

    /**
     * Gets the value of the goose property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGoose() {
        if (goose == null) {
            return false;
        } else {
            return goose;
        }
    }

    /**
     * Sets the value of the goose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoose(Boolean value) {
        this.goose = value;
    }

    /**
     * Gets the value of the gsse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGsse() {
        if (gsse == null) {
            return false;
        } else {
            return gsse;
        }
    }

    /**
     * Sets the value of the gsse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGsse(Boolean value) {
        this.gsse = value;
    }

    /**
     * Gets the value of the bufReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBufReport() {
        if (bufReport == null) {
            return false;
        } else {
            return bufReport;
        }
    }

    /**
     * Sets the value of the bufReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBufReport(Boolean value) {
        this.bufReport = value;
    }

    /**
     * Gets the value of the unbufReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUnbufReport() {
        if (unbufReport == null) {
            return false;
        } else {
            return unbufReport;
        }
    }

    /**
     * Sets the value of the unbufReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnbufReport(Boolean value) {
        this.unbufReport = value;
    }

    /**
     * Gets the value of the readLog property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReadLog() {
        if (readLog == null) {
            return false;
        } else {
            return readLog;
        }
    }

    /**
     * Sets the value of the readLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadLog(Boolean value) {
        this.readLog = value;
    }

    /**
     * Gets the value of the sv property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSv() {
        if (sv == null) {
            return false;
        } else {
            return sv;
        }
    }

    /**
     * Sets the value of the sv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSv(Boolean value) {
        this.sv = value;
    }

    /**
     * Gets the value of the supportsLdName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSupportsLdName() {
        if (supportsLdName == null) {
            return false;
        } else {
            return supportsLdName;
        }
    }

    /**
     * Sets the value of the supportsLdName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSupportsLdName(Boolean value) {
        this.supportsLdName = value;
    }

    /**
     * Gets the value of the maxAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxAttributes() {
        return maxAttributes;
    }

    /**
     * Sets the value of the maxAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxAttributes(Long value) {
        this.maxAttributes = value;
    }

    /**
     * Gets the value of the maxReports property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxReports() {
        return maxReports;
    }

    /**
     * Sets the value of the maxReports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxReports(Long value) {
        this.maxReports = value;
    }

    /**
     * Gets the value of the maxGOOSE property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxGOOSE() {
        return maxGOOSE;
    }

    /**
     * Sets the value of the maxGOOSE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxGOOSE(Long value) {
        this.maxGOOSE = value;
    }

    /**
     * Gets the value of the maxSMV property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxSMV() {
        return maxSMV;
    }

    /**
     * Sets the value of the maxSMV property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxSMV(Long value) {
        this.maxSMV = value;
    }

    /**
     * Gets the value of the rgoose property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRGOOSE() {
        if (rgoose == null) {
            return false;
        } else {
            return rgoose;
        }
    }

    /**
     * Sets the value of the rgoose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRGOOSE(Boolean value) {
        this.rgoose = value;
    }

    /**
     * Gets the value of the rsv property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRSV() {
        if (rsv == null) {
            return false;
        } else {
            return rsv;
        }
    }

    /**
     * Sets the value of the rsv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRSV(Boolean value) {
        this.rsv = value;
    }

    /**
     * Gets the value of the noIctBinding property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNoIctBinding() {
        if (noIctBinding == null) {
            return false;
        } else {
            return noIctBinding;
        }
    }

    /**
     * Sets the value of the noIctBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoIctBinding(Boolean value) {
        this.noIctBinding = value;
    }

}
