//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tControlWithIEDName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tControlWithIEDName">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tControl">
 *       &lt;sequence>
 *         &lt;element name="IEDName" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.iec.ch/61850/2003/SCL>tIEDName">
 *                 &lt;attribute name="apRef" type="{http://www.iec.ch/61850/2003/SCL}tAccessPointName" />
 *                 &lt;attribute name="ldInst" type="{http://www.iec.ch/61850/2003/SCL}tLDInst" />
 *                 &lt;attribute name="prefix" type="{http://www.iec.ch/61850/2003/SCL}tPrefix" />
 *                 &lt;attribute name="lnClass" type="{http://www.iec.ch/61850/2003/SCL}tLNClassEnum" />
 *                 &lt;attribute name="lnInst" type="{http://www.iec.ch/61850/2003/SCL}tLNInst" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="confRev" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tControlWithIEDName", propOrder = {
    "iedName"
})
@XmlSeeAlso({
    TGSEControl.class,
    TSampledValueControl.class
})
public class TControlWithIEDName
    extends TControl
{

    @XmlElement(name = "IEDName")
    protected List<TControlWithIEDName.IEDName> iedName;
    @XmlAttribute(name = "confRev")
    @XmlSchemaType(name = "unsignedInt")
    protected Long confRev;

    /**
     * Gets the value of the iedName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iedName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIEDName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TControlWithIEDName.IEDName }
     * 
     * 
     */
    public List<TControlWithIEDName.IEDName> getIEDName() {
        if (iedName == null) {
            iedName = new ArrayList<TControlWithIEDName.IEDName>();
        }
        return this.iedName;
    }

    /**
     * Gets the value of the confRev property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConfRev() {
        return confRev;
    }

    /**
     * Sets the value of the confRev property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConfRev(Long value) {
        this.confRev = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.iec.ch/61850/2003/SCL>tIEDName">
     *       &lt;attribute name="apRef" type="{http://www.iec.ch/61850/2003/SCL}tAccessPointName" />
     *       &lt;attribute name="ldInst" type="{http://www.iec.ch/61850/2003/SCL}tLDInst" />
     *       &lt;attribute name="prefix" type="{http://www.iec.ch/61850/2003/SCL}tPrefix" />
     *       &lt;attribute name="lnClass" type="{http://www.iec.ch/61850/2003/SCL}tLNClassEnum" />
     *       &lt;attribute name="lnInst" type="{http://www.iec.ch/61850/2003/SCL}tLNInst" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class IEDName {

        @XmlValue
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String value;
        @XmlAttribute(name = "apRef")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String apRef;
        @XmlAttribute(name = "ldInst")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String ldInst;
        @XmlAttribute(name = "prefix")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String prefix;
        @XmlAttribute(name = "lnClass")
        protected List<String> lnClass;
        @XmlAttribute(name = "lnInst")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String lnInst;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the apRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApRef() {
            return apRef;
        }

        /**
         * Sets the value of the apRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApRef(String value) {
            this.apRef = value;
        }

        /**
         * Gets the value of the ldInst property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLdInst() {
            return ldInst;
        }

        /**
         * Sets the value of the ldInst property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLdInst(String value) {
            this.ldInst = value;
        }

        /**
         * Gets the value of the prefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrefix() {
            return prefix;
        }

        /**
         * Sets the value of the prefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrefix(String value) {
            this.prefix = value;
        }

        /**
         * Gets the value of the lnClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lnClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLnClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getLnClass() {
            if (lnClass == null) {
                lnClass = new ArrayList<String>();
            }
            return this.lnClass;
        }

        /**
         * Gets the value of the lnInst property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLnInst() {
            return lnInst;
        }

        /**
         * Sets the value of the lnInst property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLnInst(String value) {
            this.lnInst = value;
        }

    }

}
