//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDomainLNGroupFEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tDomainLNGroupFEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;length value="4"/>
 *     &lt;pattern value="F[A-Z]*"/>
 *     &lt;enumeration value="FCNT"/>
 *     &lt;enumeration value="FCSD"/>
 *     &lt;enumeration value="FFIL"/>
 *     &lt;enumeration value="FLIM"/>
 *     &lt;enumeration value="FPID"/>
 *     &lt;enumeration value="FRMP"/>
 *     &lt;enumeration value="FSPT"/>
 *     &lt;enumeration value="FXOT"/>
 *     &lt;enumeration value="FXUT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tDomainLNGroupFEnum")
@XmlEnum
public enum TDomainLNGroupFEnum {

    FCNT,
    FCSD,
    FFIL,
    FLIM,
    FPID,
    FRMP,
    FSPT,
    FXOT,
    FXUT;

    public String value() {
        return name();
    }

    public static TDomainLNGroupFEnum fromValue(String v) {
        return valueOf(v);
    }

}
