//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDomainLNGroupTEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tDomainLNGroupTEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;length value="4"/>
 *     &lt;pattern value="T[A-Z]*"/>
 *     &lt;enumeration value="TANG"/>
 *     &lt;enumeration value="TAXD"/>
 *     &lt;enumeration value="TCTR"/>
 *     &lt;enumeration value="TDST"/>
 *     &lt;enumeration value="TFLW"/>
 *     &lt;enumeration value="TFRQ"/>
 *     &lt;enumeration value="TGSN"/>
 *     &lt;enumeration value="THUM"/>
 *     &lt;enumeration value="TLVL"/>
 *     &lt;enumeration value="TMGF"/>
 *     &lt;enumeration value="TMVM"/>
 *     &lt;enumeration value="TPOS"/>
 *     &lt;enumeration value="TPRS"/>
 *     &lt;enumeration value="TRTN"/>
 *     &lt;enumeration value="TSND"/>
 *     &lt;enumeration value="TTMP"/>
 *     &lt;enumeration value="TTNS"/>
 *     &lt;enumeration value="TVBR"/>
 *     &lt;enumeration value="TVTR"/>
 *     &lt;enumeration value="TWPH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tDomainLNGroupTEnum")
@XmlEnum
public enum TDomainLNGroupTEnum {

    TANG,
    TAXD,
    TCTR,
    TDST,
    TFLW,
    TFRQ,
    TGSN,
    THUM,
    TLVL,
    TMGF,
    TMVM,
    TPOS,
    TPRS,
    TRTN,
    TSND,
    TTMP,
    TTNS,
    TVBR,
    TVTR,
    TWPH;

    public String value() {
        return name();
    }

    public static TDomainLNGroupTEnum fromValue(String v) {
        return valueOf(v);
    }

}
