//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDomainLNGroupSEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tDomainLNGroupSEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;length value="4"/>
 *     &lt;pattern value="S[A-Z]*"/>
 *     &lt;enumeration value="SARC"/>
 *     &lt;enumeration value="SCBR"/>
 *     &lt;enumeration value="SIMG"/>
 *     &lt;enumeration value="SIML"/>
 *     &lt;enumeration value="SLTC"/>
 *     &lt;enumeration value="SOPM"/>
 *     &lt;enumeration value="SPDC"/>
 *     &lt;enumeration value="SPTR"/>
 *     &lt;enumeration value="SSWI"/>
 *     &lt;enumeration value="STMP"/>
 *     &lt;enumeration value="SVBR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tDomainLNGroupSEnum")
@XmlEnum
public enum TDomainLNGroupSEnum {

    SARC,
    SCBR,
    SIMG,
    SIML,
    SLTC,
    SOPM,
    SPDC,
    SPTR,
    SSWI,
    STMP,
    SVBR;

    public String value() {
        return name();
    }

    public static TDomainLNGroupSEnum fromValue(String v) {
        return valueOf(v);
    }

}
