//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDomainLNGroupKEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tDomainLNGroupKEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;length value="4"/>
 *     &lt;pattern value="K[A-Z]*"/>
 *     &lt;enumeration value="KFAN"/>
 *     &lt;enumeration value="KFIL"/>
 *     &lt;enumeration value="KPMP"/>
 *     &lt;enumeration value="KTNK"/>
 *     &lt;enumeration value="KVLV"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tDomainLNGroupKEnum")
@XmlEnum
public enum TDomainLNGroupKEnum {

    KFAN,
    KFIL,
    KPMP,
    KTNK,
    KVLV;

    public String value() {
        return name();
    }

    public static TDomainLNGroupKEnum fromValue(String v) {
        return valueOf(v);
    }

}
