//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tExtRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tExtRef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.iec.ch/61850/2003/SCL}agDesc"/>
 *       &lt;attribute name="iedName" type="{http://www.iec.ch/61850/2003/SCL}tIEDNameOrRelative" />
 *       &lt;attribute name="ldInst" type="{http://www.iec.ch/61850/2003/SCL}tLDInst" />
 *       &lt;attribute name="prefix" type="{http://www.iec.ch/61850/2003/SCL}tPrefix" />
 *       &lt;attribute name="lnClass" type="{http://www.iec.ch/61850/2003/SCL}tLNClassEnum" />
 *       &lt;attribute name="lnInst" type="{http://www.iec.ch/61850/2003/SCL}tLNInst" />
 *       &lt;attribute name="doName" type="{http://www.iec.ch/61850/2003/SCL}tFullDOName" />
 *       &lt;attribute name="daName" type="{http://www.iec.ch/61850/2003/SCL}tFullAttributeName" />
 *       &lt;attribute name="intAddr" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="serviceType" type="{http://www.iec.ch/61850/2003/SCL}tServiceType" />
 *       &lt;attribute name="srcLDInst" type="{http://www.iec.ch/61850/2003/SCL}tLDInst" />
 *       &lt;attribute name="srcPrefix" type="{http://www.iec.ch/61850/2003/SCL}tPrefix" />
 *       &lt;attribute name="srcLNClass" type="{http://www.iec.ch/61850/2003/SCL}tLNClassEnum" />
 *       &lt;attribute name="srcLNInst" type="{http://www.iec.ch/61850/2003/SCL}tLNInst" />
 *       &lt;attribute name="srcCBName" type="{http://www.iec.ch/61850/2003/SCL}tCBName" />
 *       &lt;attribute name="pServT" type="{http://www.iec.ch/61850/2003/SCL}tServiceType" />
 *       &lt;attribute name="pLN" type="{http://www.iec.ch/61850/2003/SCL}tLNClassEnum" />
 *       &lt;attribute name="pDO" type="{http://www.iec.ch/61850/2003/SCL}tFullDOName" />
 *       &lt;attribute name="pDA" type="{http://www.iec.ch/61850/2003/SCL}tFullAttributeName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tExtRef")
public class TExtRef {

    @XmlAttribute(name = "iedName")
    protected String iedName;
    @XmlAttribute(name = "ldInst")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ldInst;
    @XmlAttribute(name = "prefix")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String prefix;
    @XmlAttribute(name = "lnClass")
    protected List<String> lnClass;
    @XmlAttribute(name = "lnInst")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lnInst;
    @XmlAttribute(name = "doName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String doName;
    @XmlAttribute(name = "daName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String daName;
    @XmlAttribute(name = "intAddr")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String intAddr;
    @XmlAttribute(name = "serviceType")
    protected TServiceType serviceType;
    @XmlAttribute(name = "srcLDInst")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String srcLDInst;
    @XmlAttribute(name = "srcPrefix")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String srcPrefix;
    @XmlAttribute(name = "srcLNClass")
    protected List<String> srcLNClass;
    @XmlAttribute(name = "srcLNInst")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String srcLNInst;
    @XmlAttribute(name = "srcCBName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String srcCBName;
    @XmlAttribute(name = "pServT")
    protected TServiceType pServT;
    @XmlAttribute(name = "pLN")
    protected List<String> pln;
    @XmlAttribute(name = "pDO")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pdo;
    @XmlAttribute(name = "pDA")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pda;
    @XmlAttribute(name = "desc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String desc;

    /**
     * Gets the value of the iedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIedName() {
        return iedName;
    }

    /**
     * Sets the value of the iedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIedName(String value) {
        this.iedName = value;
    }

    /**
     * Gets the value of the ldInst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLdInst() {
        return ldInst;
    }

    /**
     * Sets the value of the ldInst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLdInst(String value) {
        this.ldInst = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the lnClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lnClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLnClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLnClass() {
        if (lnClass == null) {
            lnClass = new ArrayList<String>();
        }
        return this.lnClass;
    }

    /**
     * Gets the value of the lnInst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLnInst() {
        return lnInst;
    }

    /**
     * Sets the value of the lnInst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLnInst(String value) {
        this.lnInst = value;
    }

    /**
     * Gets the value of the doName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoName() {
        return doName;
    }

    /**
     * Sets the value of the doName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoName(String value) {
        this.doName = value;
    }

    /**
     * Gets the value of the daName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaName() {
        return daName;
    }

    /**
     * Sets the value of the daName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaName(String value) {
        this.daName = value;
    }

    /**
     * Gets the value of the intAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntAddr() {
        return intAddr;
    }

    /**
     * Sets the value of the intAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntAddr(String value) {
        this.intAddr = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceType }
     *     
     */
    public TServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceType }
     *     
     */
    public void setServiceType(TServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the srcLDInst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcLDInst() {
        return srcLDInst;
    }

    /**
     * Sets the value of the srcLDInst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcLDInst(String value) {
        this.srcLDInst = value;
    }

    /**
     * Gets the value of the srcPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcPrefix() {
        return srcPrefix;
    }

    /**
     * Sets the value of the srcPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcPrefix(String value) {
        this.srcPrefix = value;
    }

    /**
     * Gets the value of the srcLNClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the srcLNClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSrcLNClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSrcLNClass() {
        if (srcLNClass == null) {
            srcLNClass = new ArrayList<String>();
        }
        return this.srcLNClass;
    }

    /**
     * Gets the value of the srcLNInst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcLNInst() {
        return srcLNInst;
    }

    /**
     * Sets the value of the srcLNInst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcLNInst(String value) {
        this.srcLNInst = value;
    }

    /**
     * Gets the value of the srcCBName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcCBName() {
        return srcCBName;
    }

    /**
     * Sets the value of the srcCBName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcCBName(String value) {
        this.srcCBName = value;
    }

    /**
     * Gets the value of the pServT property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceType }
     *     
     */
    public TServiceType getPServT() {
        return pServT;
    }

    /**
     * Sets the value of the pServT property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceType }
     *     
     */
    public void setPServT(TServiceType value) {
        this.pServT = value;
    }

    /**
     * Gets the value of the pln property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pln property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPLN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPLN() {
        if (pln == null) {
            pln = new ArrayList<String>();
        }
        return this.pln;
    }

    /**
     * Gets the value of the pdo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDO() {
        return pdo;
    }

    /**
     * Sets the value of the pdo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDO(String value) {
        this.pdo = value;
    }

    /**
     * Gets the value of the pda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDA() {
        return pda;
    }

    /**
     * Sets the value of the pda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDA(String value) {
        this.pda = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        if (desc == null) {
            return "";
        } else {
            return desc;
        }
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

}
