//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tGOOSEcapabilities complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tGOOSEcapabilities">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceWithMax">
 *       &lt;attribute name="fixedOffs" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="goose" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="rGOOSE" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tGOOSEcapabilities")
public class TGOOSEcapabilities
    extends TServiceWithMax
{

    @XmlAttribute(name = "fixedOffs")
    protected Boolean fixedOffs;
    @XmlAttribute(name = "goose")
    protected Boolean goose;
    @XmlAttribute(name = "rGOOSE")
    protected Boolean rgoose;

    /**
     * Gets the value of the fixedOffs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFixedOffs() {
        if (fixedOffs == null) {
            return false;
        } else {
            return fixedOffs;
        }
    }

    /**
     * Sets the value of the fixedOffs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFixedOffs(Boolean value) {
        this.fixedOffs = value;
    }

    /**
     * Gets the value of the goose property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGoose() {
        if (goose == null) {
            return true;
        } else {
            return goose;
        }
    }

    /**
     * Sets the value of the goose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoose(Boolean value) {
        this.goose = value;
    }

    /**
     * Gets the value of the rgoose property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRGOOSE() {
        if (rgoose == null) {
            return false;
        } else {
            return rgoose;
        }
    }

    /**
     * Sets the value of the rgoose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRGOOSE(Boolean value) {
        this.rgoose = value;
    }

}
