//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tGSESettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tGSESettings">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceSettings">
 *       &lt;sequence>
 *         &lt;element name="McSecurity" type="{http://www.iec.ch/61850/2003/SCL}tMcSecurity" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="appID" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="dataLabel" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="kdaParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tGSESettings", propOrder = {
    "mcSecurity"
})
public class TGSESettings
    extends TServiceSettings
{

    @XmlElement(name = "McSecurity")
    protected TMcSecurity mcSecurity;
    @XmlAttribute(name = "appID")
    protected TServiceSettingsEnum appID;
    @XmlAttribute(name = "dataLabel")
    protected TServiceSettingsEnum dataLabel;
    @XmlAttribute(name = "kdaParticipant")
    protected Boolean kdaParticipant;

    /**
     * Gets the value of the mcSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link TMcSecurity }
     *     
     */
    public TMcSecurity getMcSecurity() {
        return mcSecurity;
    }

    /**
     * Sets the value of the mcSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMcSecurity }
     *     
     */
    public void setMcSecurity(TMcSecurity value) {
        this.mcSecurity = value;
    }

    /**
     * Gets the value of the appID property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getAppID() {
        if (appID == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return appID;
        }
    }

    /**
     * Sets the value of the appID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setAppID(TServiceSettingsEnum value) {
        this.appID = value;
    }

    /**
     * Gets the value of the dataLabel property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getDataLabel() {
        if (dataLabel == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return dataLabel;
        }
    }

    /**
     * Sets the value of the dataLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setDataLabel(TServiceSettingsEnum value) {
        this.dataLabel = value;
    }

    /**
     * Gets the value of the kdaParticipant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isKdaParticipant() {
        if (kdaParticipant == null) {
            return false;
        } else {
            return kdaParticipant;
        }
    }

    /**
     * Sets the value of the kdaParticipant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKdaParticipant(Boolean value) {
        this.kdaParticipant = value;
    }

}
