//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tGSEControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tGSEControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tControlWithIEDName">
 *       &lt;sequence>
 *         &lt;element name="Protocol" type="{http://www.iec.ch/61850/2003/SCL}tProtocol" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.iec.ch/61850/2003/SCL}tGSEControlTypeEnum" default="GOOSE" />
 *       &lt;attribute name="appID" use="required" type="{http://www.iec.ch/61850/2003/SCL}tMessageID" />
 *       &lt;attribute name="fixedOffs" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="securityEnable" type="{http://www.iec.ch/61850/2003/SCL}tPredefinedTypeOfSecurityEnum" default="None" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tGSEControl", propOrder = {
    "protocol"
})
public class TGSEControl
    extends TControlWithIEDName
{

    @XmlElement(name = "Protocol")
    protected TProtocol protocol;
    @XmlAttribute(name = "type")
    protected TGSEControlTypeEnum type;
    @XmlAttribute(name = "appID", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String appID;
    @XmlAttribute(name = "fixedOffs")
    protected Boolean fixedOffs;
    @XmlAttribute(name = "securityEnable")
    protected TPredefinedTypeOfSecurityEnum securityEnable;

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link TProtocol }
     *     
     */
    public TProtocol getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProtocol }
     *     
     */
    public void setProtocol(TProtocol value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TGSEControlTypeEnum }
     *     
     */
    public TGSEControlTypeEnum getType() {
        if (type == null) {
            return TGSEControlTypeEnum.GOOSE;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGSEControlTypeEnum }
     *     
     */
    public void setType(TGSEControlTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the appID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppID() {
        return appID;
    }

    /**
     * Sets the value of the appID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppID(String value) {
        this.appID = value;
    }

    /**
     * Gets the value of the fixedOffs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isFixedOffs() {
        if (fixedOffs == null) {
            return false;
        } else {
            return fixedOffs;
        }
    }

    /**
     * Sets the value of the fixedOffs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFixedOffs(Boolean value) {
        this.fixedOffs = value;
    }

    /**
     * Gets the value of the securityEnable property.
     * 
     * @return
     *     possible object is
     *     {@link TPredefinedTypeOfSecurityEnum }
     *     
     */
    public TPredefinedTypeOfSecurityEnum getSecurityEnable() {
        if (securityEnable == null) {
            return TPredefinedTypeOfSecurityEnum.NONE;
        } else {
            return securityEnable;
        }
    }

    /**
     * Sets the value of the securityEnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPredefinedTypeOfSecurityEnum }
     *     
     */
    public void setSecurityEnable(TPredefinedTypeOfSecurityEnum value) {
        this.securityEnable = value;
    }

}
