//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tIED complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tIED">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tUnNaming">
 *       &lt;sequence>
 *         &lt;element name="Services" type="{http://www.iec.ch/61850/2003/SCL}tServices" minOccurs="0"/>
 *         &lt;element name="AccessPoint" type="{http://www.iec.ch/61850/2003/SCL}tAccessPoint" maxOccurs="unbounded"/>
 *         &lt;element name="KDC" type="{http://www.iec.ch/61850/2003/SCL}tKDC" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.iec.ch/61850/2003/SCL}tIEDName" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="configVersion" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;attribute name="originalSclVersion" type="{http://www.iec.ch/61850/2003/SCL}tSclVersion" default="2003" />
 *       &lt;attribute name="originalSclRevision" type="{http://www.iec.ch/61850/2003/SCL}tSclRevision" default="A" />
 *       &lt;attribute name="originalSclRelease" type="{http://www.iec.ch/61850/2003/SCL}tSclRelease" default="1" />
 *       &lt;attribute name="engRight" type="{http://www.iec.ch/61850/2003/SCL}tRightEnum" default="full" />
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tIED", propOrder = {
    "services",
    "accessPoint",
    "kdc"
})
public class TIED
    extends TUnNaming
{

    @XmlElement(name = "Services")
    protected TServices services;
    @XmlElement(name = "AccessPoint", required = true)
    protected List<TAccessPoint> accessPoint;
    @XmlElement(name = "KDC")
    protected List<TKDC> kdc;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "type")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String type;
    @XmlAttribute(name = "manufacturer")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String manufacturer;
    @XmlAttribute(name = "configVersion")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String configVersion;
    @XmlAttribute(name = "originalSclVersion")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String originalSclVersion;
    @XmlAttribute(name = "originalSclRevision")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originalSclRevision;
    @XmlAttribute(name = "originalSclRelease")
    protected Short originalSclRelease;
    @XmlAttribute(name = "engRight")
    protected TRightEnum engRight;
    @XmlAttribute(name = "owner")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String owner;

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link TServices }
     *     
     */
    public TServices getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServices }
     *     
     */
    public void setServices(TServices value) {
        this.services = value;
    }

    /**
     * Gets the value of the accessPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAccessPoint }
     * 
     * 
     */
    public List<TAccessPoint> getAccessPoint() {
        if (accessPoint == null) {
            accessPoint = new ArrayList<TAccessPoint>();
        }
        return this.accessPoint;
    }

    /**
     * Gets the value of the kdc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kdc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKDC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TKDC }
     * 
     * 
     */
    public List<TKDC> getKDC() {
        if (kdc == null) {
            kdc = new ArrayList<TKDC>();
        }
        return this.kdc;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the configVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigVersion() {
        return configVersion;
    }

    /**
     * Sets the value of the configVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigVersion(String value) {
        this.configVersion = value;
    }

    /**
     * Gets the value of the originalSclVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalSclVersion() {
        if (originalSclVersion == null) {
            return "2003";
        } else {
            return originalSclVersion;
        }
    }

    /**
     * Sets the value of the originalSclVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalSclVersion(String value) {
        this.originalSclVersion = value;
    }

    /**
     * Gets the value of the originalSclRevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalSclRevision() {
        if (originalSclRevision == null) {
            return "A";
        } else {
            return originalSclRevision;
        }
    }

    /**
     * Sets the value of the originalSclRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalSclRevision(String value) {
        this.originalSclRevision = value;
    }

    /**
     * Gets the value of the originalSclRelease property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public short getOriginalSclRelease() {
        if (originalSclRelease == null) {
            return ((short) 1);
        } else {
            return originalSclRelease;
        }
    }

    /**
     * Sets the value of the originalSclRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setOriginalSclRelease(Short value) {
        this.originalSclRelease = value;
    }

    /**
     * Gets the value of the engRight property.
     * 
     * @return
     *     possible object is
     *     {@link TRightEnum }
     *     
     */
    public TRightEnum getEngRight() {
        if (engRight == null) {
            return TRightEnum.FULL;
        } else {
            return engRight;
        }
    }

    /**
     * Sets the value of the engRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRightEnum }
     *     
     */
    public void setEngRight(TRightEnum value) {
        this.engRight = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

}
