//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tKDC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tKDC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="iedName" use="required" type="{http://www.iec.ch/61850/2003/SCL}tIEDName" />
 *       &lt;attribute name="apName" use="required" type="{http://www.iec.ch/61850/2003/SCL}tAccessPointName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tKDC")
public class TKDC {

    @XmlAttribute(name = "iedName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String iedName;
    @XmlAttribute(name = "apName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String apName;

    /**
     * Gets the value of the iedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIedName() {
        return iedName;
    }

    /**
     * Sets the value of the iedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIedName(String value) {
        this.iedName = value;
    }

    /**
     * Gets the value of the apName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApName() {
        return apName;
    }

    /**
     * Sets the value of the apName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApName(String value) {
        this.apName = value;
    }

}
