//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPredefinedAttributeNameEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tPredefinedAttributeNameEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="Test"/>
 *     &lt;enumeration value="Check"/>
 *     &lt;enumeration value="SIUnit"/>
 *     &lt;enumeration value="Oper"/>
 *     &lt;enumeration value="SBO"/>
 *     &lt;enumeration value="SBOw"/>
 *     &lt;enumeration value="Cancel"/>
 *     &lt;enumeration value="Addr"/>
 *     &lt;enumeration value="PRIORITY"/>
 *     &lt;enumeration value="VID"/>
 *     &lt;enumeration value="APPID"/>
 *     &lt;enumeration value="TransportInUse"/>
 *     &lt;enumeration value="IPClassOfTraffic"/>
 *     &lt;enumeration value="IPv6FlowLabel"/>
 *     &lt;enumeration value="IPAddressLength"/>
 *     &lt;enumeration value="IPAddress"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tPredefinedAttributeNameEnum")
@XmlEnum
public enum TPredefinedAttributeNameEnum {

    T("T"),
    @XmlEnumValue("Test")
    TEST("Test"),
    @XmlEnumValue("Check")
    CHECK("Check"),
    @XmlEnumValue("SIUnit")
    SI_UNIT("SIUnit"),
    @XmlEnumValue("Oper")
    OPER("Oper"),
    SBO("SBO"),
    @XmlEnumValue("SBOw")
    SB_OW("SBOw"),
    @XmlEnumValue("Cancel")
    CANCEL("Cancel"),
    @XmlEnumValue("Addr")
    ADDR("Addr"),
    PRIORITY("PRIORITY"),
    VID("VID"),
    APPID("APPID"),
    @XmlEnumValue("TransportInUse")
    TRANSPORT_IN_USE("TransportInUse"),
    @XmlEnumValue("IPClassOfTraffic")
    IP_CLASS_OF_TRAFFIC("IPClassOfTraffic"),
    @XmlEnumValue("IPv6FlowLabel")
    I_PV_6_FLOW_LABEL("IPv6FlowLabel"),
    @XmlEnumValue("IPAddressLength")
    IP_ADDRESS_LENGTH("IPAddressLength"),
    @XmlEnumValue("IPAddress")
    IP_ADDRESS("IPAddress");
    private final String value;

    TPredefinedAttributeNameEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TPredefinedAttributeNameEnum fromValue(String v) {
        for (TPredefinedAttributeNameEnum c: TPredefinedAttributeNameEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
