//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tPredefinedCDCEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tPredefinedCDCEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;enumeration value="SPS"/>
 *     &lt;enumeration value="DPS"/>
 *     &lt;enumeration value="INS"/>
 *     &lt;enumeration value="ENS"/>
 *     &lt;enumeration value="ACT"/>
 *     &lt;enumeration value="ACD"/>
 *     &lt;enumeration value="SEC"/>
 *     &lt;enumeration value="BCR"/>
 *     &lt;enumeration value="HST"/>
 *     &lt;enumeration value="VSS"/>
 *     &lt;enumeration value="MV"/>
 *     &lt;enumeration value="CMV"/>
 *     &lt;enumeration value="SAV"/>
 *     &lt;enumeration value="WYE"/>
 *     &lt;enumeration value="DEL"/>
 *     &lt;enumeration value="SEQ"/>
 *     &lt;enumeration value="HMV"/>
 *     &lt;enumeration value="HWYE"/>
 *     &lt;enumeration value="HDEL"/>
 *     &lt;enumeration value="SPC"/>
 *     &lt;enumeration value="DPC"/>
 *     &lt;enumeration value="INC"/>
 *     &lt;enumeration value="ENC"/>
 *     &lt;enumeration value="BSC"/>
 *     &lt;enumeration value="ISC"/>
 *     &lt;enumeration value="APC"/>
 *     &lt;enumeration value="BAC"/>
 *     &lt;enumeration value="SPG"/>
 *     &lt;enumeration value="ING"/>
 *     &lt;enumeration value="ENG"/>
 *     &lt;enumeration value="ORG"/>
 *     &lt;enumeration value="TSG"/>
 *     &lt;enumeration value="CUG"/>
 *     &lt;enumeration value="VSG"/>
 *     &lt;enumeration value="ASG"/>
 *     &lt;enumeration value="CURVE"/>
 *     &lt;enumeration value="CSG"/>
 *     &lt;enumeration value="DPL"/>
 *     &lt;enumeration value="LPL"/>
 *     &lt;enumeration value="CSD"/>
 *     &lt;enumeration value="CST"/>
 *     &lt;enumeration value="BTS"/>
 *     &lt;enumeration value="UTS"/>
 *     &lt;enumeration value="LTS"/>
 *     &lt;enumeration value="GTS"/>
 *     &lt;enumeration value="MTS"/>
 *     &lt;enumeration value="NTS"/>
 *     &lt;enumeration value="STS"/>
 *     &lt;enumeration value="CTS"/>
 *     &lt;enumeration value="OTS"/>
 *     &lt;enumeration value="VSD"/>
 *     &lt;enumeration value="ORS"/>
 *     &lt;enumeration value="TCS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tPredefinedCDCEnum")
@XmlEnum
public enum TPredefinedCDCEnum {

    SPS,
    DPS,
    INS,
    ENS,
    ACT,
    ACD,
    SEC,
    BCR,
    HST,
    VSS,
    MV,
    CMV,
    SAV,
    WYE,
    DEL,
    SEQ,
    HMV,
    HWYE,
    HDEL,
    SPC,
    DPC,
    INC,
    ENC,
    BSC,
    ISC,
    APC,
    BAC,
    SPG,
    ING,
    ENG,
    ORG,
    TSG,
    CUG,
    VSG,
    ASG,
    CURVE,
    CSG,
    DPL,
    LPL,
    CSD,
    CST,
    BTS,
    UTS,
    LTS,
    GTS,
    MTS,
    NTS,
    STS,
    CTS,
    OTS,
    VSD,
    ORS,
    TCS;

    public String value() {
        return name();
    }

    public static TPredefinedCDCEnum fromValue(String v) {
        return valueOf(v);
    }

}
