//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tReportSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tReportSettings">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceSettings">
 *       &lt;attribute name="rptID" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="optFields" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="bufTime" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="trgOps" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="intgPd" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="resvTms" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tReportSettings")
public class TReportSettings
    extends TServiceSettings
{

    @XmlAttribute(name = "rptID")
    protected TServiceSettingsEnum rptID;
    @XmlAttribute(name = "optFields")
    protected TServiceSettingsEnum optFields;
    @XmlAttribute(name = "bufTime")
    protected TServiceSettingsEnum bufTime;
    @XmlAttribute(name = "trgOps")
    protected TServiceSettingsEnum trgOps;
    @XmlAttribute(name = "intgPd")
    protected TServiceSettingsEnum intgPd;
    @XmlAttribute(name = "resvTms")
    protected Boolean resvTms;
    @XmlAttribute(name = "owner")
    protected Boolean owner;

    /**
     * Gets the value of the rptID property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getRptID() {
        if (rptID == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return rptID;
        }
    }

    /**
     * Sets the value of the rptID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setRptID(TServiceSettingsEnum value) {
        this.rptID = value;
    }

    /**
     * Gets the value of the optFields property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getOptFields() {
        if (optFields == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return optFields;
        }
    }

    /**
     * Sets the value of the optFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setOptFields(TServiceSettingsEnum value) {
        this.optFields = value;
    }

    /**
     * Gets the value of the bufTime property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getBufTime() {
        if (bufTime == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return bufTime;
        }
    }

    /**
     * Sets the value of the bufTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setBufTime(TServiceSettingsEnum value) {
        this.bufTime = value;
    }

    /**
     * Gets the value of the trgOps property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getTrgOps() {
        if (trgOps == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return trgOps;
        }
    }

    /**
     * Sets the value of the trgOps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setTrgOps(TServiceSettingsEnum value) {
        this.trgOps = value;
    }

    /**
     * Gets the value of the intgPd property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getIntgPd() {
        if (intgPd == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return intgPd;
        }
    }

    /**
     * Sets the value of the intgPd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setIntgPd(TServiceSettingsEnum value) {
        this.intgPd = value;
    }

    /**
     * Gets the value of the resvTms property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isResvTms() {
        if (resvTms == null) {
            return false;
        } else {
            return resvTms;
        }
    }

    /**
     * Sets the value of the resvTms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResvTms(Boolean value) {
        this.resvTms = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOwner() {
        if (owner == null) {
            return false;
        } else {
            return owner;
        }
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOwner(Boolean value) {
        this.owner = value;
    }

}
