//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tServices complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tServices">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="DynAssociation" type="{http://www.iec.ch/61850/2003/SCL}tServiceWithOptionalMax" minOccurs="0"/>
 *         &lt;element name="SettingGroups" type="{http://www.iec.ch/61850/2003/SCL}tSettingGroups" minOccurs="0"/>
 *         &lt;element name="GetDirectory" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="GetDataObjectDefinition" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="DataObjectDirectory" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="GetDataSetValue" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="SetDataSetValue" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="DataSetDirectory" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="ConfDataSet" type="{http://www.iec.ch/61850/2003/SCL}tServiceForConfDataSet" minOccurs="0"/>
 *         &lt;element name="DynDataSet" type="{http://www.iec.ch/61850/2003/SCL}tServiceWithMaxAndMaxAttributes" minOccurs="0"/>
 *         &lt;element name="ReadWrite" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="TimerActivatedControl" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="ConfReportControl" type="{http://www.iec.ch/61850/2003/SCL}tServiceConfReportControl" minOccurs="0"/>
 *         &lt;element name="GetCBValues" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="ConfLogControl" type="{http://www.iec.ch/61850/2003/SCL}tServiceWithMaxNonZero" minOccurs="0"/>
 *         &lt;element name="ReportSettings" type="{http://www.iec.ch/61850/2003/SCL}tReportSettings" minOccurs="0"/>
 *         &lt;element name="LogSettings" type="{http://www.iec.ch/61850/2003/SCL}tLogSettings" minOccurs="0"/>
 *         &lt;element name="GSESettings" type="{http://www.iec.ch/61850/2003/SCL}tGSESettings" minOccurs="0"/>
 *         &lt;element name="SMVSettings" type="{http://www.iec.ch/61850/2003/SCL}tSMVSettings" minOccurs="0"/>
 *         &lt;element name="GSEDir" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="GOOSE" type="{http://www.iec.ch/61850/2003/SCL}tGOOSEcapabilities" minOccurs="0"/>
 *         &lt;element name="GSSE" type="{http://www.iec.ch/61850/2003/SCL}tServiceWithMax" minOccurs="0"/>
 *         &lt;element name="SMVsc" type="{http://www.iec.ch/61850/2003/SCL}tSMVsc" minOccurs="0"/>
 *         &lt;element name="FileHandling" type="{http://www.iec.ch/61850/2003/SCL}tFileHandling" minOccurs="0"/>
 *         &lt;element name="ConfLNs" type="{http://www.iec.ch/61850/2003/SCL}tConfLNs" minOccurs="0"/>
 *         &lt;element name="ClientServices" type="{http://www.iec.ch/61850/2003/SCL}tClientServices" minOccurs="0"/>
 *         &lt;element name="ConfLdName" type="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo" minOccurs="0"/>
 *         &lt;element name="SupSubscription" type="{http://www.iec.ch/61850/2003/SCL}tSupSubscription" minOccurs="0"/>
 *         &lt;element name="ConfSigRef" type="{http://www.iec.ch/61850/2003/SCL}tServiceWithMaxNonZero" minOccurs="0"/>
 *         &lt;element name="ValueHandling" type="{http://www.iec.ch/61850/2003/SCL}tValueHandling" minOccurs="0"/>
 *         &lt;element name="RedProt" type="{http://www.iec.ch/61850/2003/SCL}tRedProt" minOccurs="0"/>
 *         &lt;element name="TimeSyncProt" type="{http://www.iec.ch/61850/2003/SCL}tTimeSyncProt" minOccurs="0"/>
 *         &lt;element name="CommProt" type="{http://www.iec.ch/61850/2003/SCL}tCommProt" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="nameLength" default="32">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;pattern value="32"/>
 *             &lt;pattern value="64"/>
 *             &lt;pattern value="6[5-9]"/>
 *             &lt;pattern value="[7-9]\d"/>
 *             &lt;pattern value="[1-9]\d\d+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tServices", propOrder = {

})
public class TServices {

    @XmlElement(name = "DynAssociation")
    protected TServiceWithOptionalMax dynAssociation;
    @XmlElement(name = "SettingGroups")
    protected TSettingGroups settingGroups;
    @XmlElement(name = "GetDirectory")
    protected TServiceYesNo getDirectory;
    @XmlElement(name = "GetDataObjectDefinition")
    protected TServiceYesNo getDataObjectDefinition;
    @XmlElement(name = "DataObjectDirectory")
    protected TServiceYesNo dataObjectDirectory;
    @XmlElement(name = "GetDataSetValue")
    protected TServiceYesNo getDataSetValue;
    @XmlElement(name = "SetDataSetValue")
    protected TServiceYesNo setDataSetValue;
    @XmlElement(name = "DataSetDirectory")
    protected TServiceYesNo dataSetDirectory;
    @XmlElement(name = "ConfDataSet")
    protected TServiceForConfDataSet confDataSet;
    @XmlElement(name = "DynDataSet")
    protected TServiceWithMaxAndMaxAttributes dynDataSet;
    @XmlElement(name = "ReadWrite")
    protected TServiceYesNo readWrite;
    @XmlElement(name = "TimerActivatedControl")
    protected TServiceYesNo timerActivatedControl;
    @XmlElement(name = "ConfReportControl")
    protected TServiceConfReportControl confReportControl;
    @XmlElement(name = "GetCBValues")
    protected TServiceYesNo getCBValues;
    @XmlElement(name = "ConfLogControl")
    protected TServiceWithMaxNonZero confLogControl;
    @XmlElement(name = "ReportSettings")
    protected TReportSettings reportSettings;
    @XmlElement(name = "LogSettings")
    protected TLogSettings logSettings;
    @XmlElement(name = "GSESettings")
    protected TGSESettings gseSettings;
    @XmlElement(name = "SMVSettings")
    protected TSMVSettings smvSettings;
    @XmlElement(name = "GSEDir")
    protected TServiceYesNo gseDir;
    @XmlElement(name = "GOOSE")
    protected TGOOSEcapabilities goose;
    @XmlElement(name = "GSSE")
    protected TServiceWithMax gsse;
    @XmlElement(name = "SMVsc")
    protected TSMVsc smVsc;
    @XmlElement(name = "FileHandling")
    protected TFileHandling fileHandling;
    @XmlElement(name = "ConfLNs")
    protected TConfLNs confLNs;
    @XmlElement(name = "ClientServices")
    protected TClientServices clientServices;
    @XmlElement(name = "ConfLdName")
    protected TServiceYesNo confLdName;
    @XmlElement(name = "SupSubscription")
    protected TSupSubscription supSubscription;
    @XmlElement(name = "ConfSigRef")
    protected TServiceWithMaxNonZero confSigRef;
    @XmlElement(name = "ValueHandling")
    protected TValueHandling valueHandling;
    @XmlElement(name = "RedProt")
    protected TRedProt redProt;
    @XmlElement(name = "TimeSyncProt")
    protected TTimeSyncProt timeSyncProt;
    @XmlElement(name = "CommProt")
    protected TCommProt commProt;
    @XmlAttribute(name = "nameLength")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nameLength;

    /**
     * Gets the value of the dynAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithOptionalMax }
     *     
     */
    public TServiceWithOptionalMax getDynAssociation() {
        return dynAssociation;
    }

    /**
     * Sets the value of the dynAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithOptionalMax }
     *     
     */
    public void setDynAssociation(TServiceWithOptionalMax value) {
        this.dynAssociation = value;
    }

    /**
     * Gets the value of the settingGroups property.
     * 
     * @return
     *     possible object is
     *     {@link TSettingGroups }
     *     
     */
    public TSettingGroups getSettingGroups() {
        return settingGroups;
    }

    /**
     * Sets the value of the settingGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSettingGroups }
     *     
     */
    public void setSettingGroups(TSettingGroups value) {
        this.settingGroups = value;
    }

    /**
     * Gets the value of the getDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGetDirectory() {
        return getDirectory;
    }

    /**
     * Sets the value of the getDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGetDirectory(TServiceYesNo value) {
        this.getDirectory = value;
    }

    /**
     * Gets the value of the getDataObjectDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGetDataObjectDefinition() {
        return getDataObjectDefinition;
    }

    /**
     * Sets the value of the getDataObjectDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGetDataObjectDefinition(TServiceYesNo value) {
        this.getDataObjectDefinition = value;
    }

    /**
     * Gets the value of the dataObjectDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getDataObjectDirectory() {
        return dataObjectDirectory;
    }

    /**
     * Sets the value of the dataObjectDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setDataObjectDirectory(TServiceYesNo value) {
        this.dataObjectDirectory = value;
    }

    /**
     * Gets the value of the getDataSetValue property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGetDataSetValue() {
        return getDataSetValue;
    }

    /**
     * Sets the value of the getDataSetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGetDataSetValue(TServiceYesNo value) {
        this.getDataSetValue = value;
    }

    /**
     * Gets the value of the setDataSetValue property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getSetDataSetValue() {
        return setDataSetValue;
    }

    /**
     * Sets the value of the setDataSetValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setSetDataSetValue(TServiceYesNo value) {
        this.setDataSetValue = value;
    }

    /**
     * Gets the value of the dataSetDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getDataSetDirectory() {
        return dataSetDirectory;
    }

    /**
     * Sets the value of the dataSetDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setDataSetDirectory(TServiceYesNo value) {
        this.dataSetDirectory = value;
    }

    /**
     * Gets the value of the confDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceForConfDataSet }
     *     
     */
    public TServiceForConfDataSet getConfDataSet() {
        return confDataSet;
    }

    /**
     * Sets the value of the confDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceForConfDataSet }
     *     
     */
    public void setConfDataSet(TServiceForConfDataSet value) {
        this.confDataSet = value;
    }

    /**
     * Gets the value of the dynDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMaxAndMaxAttributes }
     *     
     */
    public TServiceWithMaxAndMaxAttributes getDynDataSet() {
        return dynDataSet;
    }

    /**
     * Sets the value of the dynDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMaxAndMaxAttributes }
     *     
     */
    public void setDynDataSet(TServiceWithMaxAndMaxAttributes value) {
        this.dynDataSet = value;
    }

    /**
     * Gets the value of the readWrite property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getReadWrite() {
        return readWrite;
    }

    /**
     * Sets the value of the readWrite property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setReadWrite(TServiceYesNo value) {
        this.readWrite = value;
    }

    /**
     * Gets the value of the timerActivatedControl property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getTimerActivatedControl() {
        return timerActivatedControl;
    }

    /**
     * Sets the value of the timerActivatedControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setTimerActivatedControl(TServiceYesNo value) {
        this.timerActivatedControl = value;
    }

    /**
     * Gets the value of the confReportControl property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceConfReportControl }
     *     
     */
    public TServiceConfReportControl getConfReportControl() {
        return confReportControl;
    }

    /**
     * Sets the value of the confReportControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceConfReportControl }
     *     
     */
    public void setConfReportControl(TServiceConfReportControl value) {
        this.confReportControl = value;
    }

    /**
     * Gets the value of the getCBValues property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGetCBValues() {
        return getCBValues;
    }

    /**
     * Sets the value of the getCBValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGetCBValues(TServiceYesNo value) {
        this.getCBValues = value;
    }

    /**
     * Gets the value of the confLogControl property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMaxNonZero }
     *     
     */
    public TServiceWithMaxNonZero getConfLogControl() {
        return confLogControl;
    }

    /**
     * Sets the value of the confLogControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMaxNonZero }
     *     
     */
    public void setConfLogControl(TServiceWithMaxNonZero value) {
        this.confLogControl = value;
    }

    /**
     * Gets the value of the reportSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TReportSettings }
     *     
     */
    public TReportSettings getReportSettings() {
        return reportSettings;
    }

    /**
     * Sets the value of the reportSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TReportSettings }
     *     
     */
    public void setReportSettings(TReportSettings value) {
        this.reportSettings = value;
    }

    /**
     * Gets the value of the logSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TLogSettings }
     *     
     */
    public TLogSettings getLogSettings() {
        return logSettings;
    }

    /**
     * Sets the value of the logSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLogSettings }
     *     
     */
    public void setLogSettings(TLogSettings value) {
        this.logSettings = value;
    }

    /**
     * Gets the value of the gseSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TGSESettings }
     *     
     */
    public TGSESettings getGSESettings() {
        return gseSettings;
    }

    /**
     * Sets the value of the gseSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGSESettings }
     *     
     */
    public void setGSESettings(TGSESettings value) {
        this.gseSettings = value;
    }

    /**
     * Gets the value of the smvSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TSMVSettings }
     *     
     */
    public TSMVSettings getSMVSettings() {
        return smvSettings;
    }

    /**
     * Sets the value of the smvSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSMVSettings }
     *     
     */
    public void setSMVSettings(TSMVSettings value) {
        this.smvSettings = value;
    }

    /**
     * Gets the value of the gseDir property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getGSEDir() {
        return gseDir;
    }

    /**
     * Sets the value of the gseDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setGSEDir(TServiceYesNo value) {
        this.gseDir = value;
    }

    /**
     * Gets the value of the goose property.
     * 
     * @return
     *     possible object is
     *     {@link TGOOSEcapabilities }
     *     
     */
    public TGOOSEcapabilities getGOOSE() {
        return goose;
    }

    /**
     * Sets the value of the goose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGOOSEcapabilities }
     *     
     */
    public void setGOOSE(TGOOSEcapabilities value) {
        this.goose = value;
    }

    /**
     * Gets the value of the gsse property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMax }
     *     
     */
    public TServiceWithMax getGSSE() {
        return gsse;
    }

    /**
     * Sets the value of the gsse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMax }
     *     
     */
    public void setGSSE(TServiceWithMax value) {
        this.gsse = value;
    }

    /**
     * Gets the value of the smVsc property.
     * 
     * @return
     *     possible object is
     *     {@link TSMVsc }
     *     
     */
    public TSMVsc getSMVsc() {
        return smVsc;
    }

    /**
     * Sets the value of the smVsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSMVsc }
     *     
     */
    public void setSMVsc(TSMVsc value) {
        this.smVsc = value;
    }

    /**
     * Gets the value of the fileHandling property.
     * 
     * @return
     *     possible object is
     *     {@link TFileHandling }
     *     
     */
    public TFileHandling getFileHandling() {
        return fileHandling;
    }

    /**
     * Sets the value of the fileHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFileHandling }
     *     
     */
    public void setFileHandling(TFileHandling value) {
        this.fileHandling = value;
    }

    /**
     * Gets the value of the confLNs property.
     * 
     * @return
     *     possible object is
     *     {@link TConfLNs }
     *     
     */
    public TConfLNs getConfLNs() {
        return confLNs;
    }

    /**
     * Sets the value of the confLNs property.
     * 
     * @param value
     *     allowed object is
     *     {@link TConfLNs }
     *     
     */
    public void setConfLNs(TConfLNs value) {
        this.confLNs = value;
    }

    /**
     * Gets the value of the clientServices property.
     * 
     * @return
     *     possible object is
     *     {@link TClientServices }
     *     
     */
    public TClientServices getClientServices() {
        return clientServices;
    }

    /**
     * Sets the value of the clientServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link TClientServices }
     *     
     */
    public void setClientServices(TClientServices value) {
        this.clientServices = value;
    }

    /**
     * Gets the value of the confLdName property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceYesNo }
     *     
     */
    public TServiceYesNo getConfLdName() {
        return confLdName;
    }

    /**
     * Sets the value of the confLdName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceYesNo }
     *     
     */
    public void setConfLdName(TServiceYesNo value) {
        this.confLdName = value;
    }

    /**
     * Gets the value of the supSubscription property.
     * 
     * @return
     *     possible object is
     *     {@link TSupSubscription }
     *     
     */
    public TSupSubscription getSupSubscription() {
        return supSubscription;
    }

    /**
     * Sets the value of the supSubscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSupSubscription }
     *     
     */
    public void setSupSubscription(TSupSubscription value) {
        this.supSubscription = value;
    }

    /**
     * Gets the value of the confSigRef property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceWithMaxNonZero }
     *     
     */
    public TServiceWithMaxNonZero getConfSigRef() {
        return confSigRef;
    }

    /**
     * Sets the value of the confSigRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceWithMaxNonZero }
     *     
     */
    public void setConfSigRef(TServiceWithMaxNonZero value) {
        this.confSigRef = value;
    }

    /**
     * Gets the value of the valueHandling property.
     * 
     * @return
     *     possible object is
     *     {@link TValueHandling }
     *     
     */
    public TValueHandling getValueHandling() {
        return valueHandling;
    }

    /**
     * Sets the value of the valueHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link TValueHandling }
     *     
     */
    public void setValueHandling(TValueHandling value) {
        this.valueHandling = value;
    }

    /**
     * Gets the value of the redProt property.
     * 
     * @return
     *     possible object is
     *     {@link TRedProt }
     *     
     */
    public TRedProt getRedProt() {
        return redProt;
    }

    /**
     * Sets the value of the redProt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRedProt }
     *     
     */
    public void setRedProt(TRedProt value) {
        this.redProt = value;
    }

    /**
     * Gets the value of the timeSyncProt property.
     * 
     * @return
     *     possible object is
     *     {@link TTimeSyncProt }
     *     
     */
    public TTimeSyncProt getTimeSyncProt() {
        return timeSyncProt;
    }

    /**
     * Sets the value of the timeSyncProt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTimeSyncProt }
     *     
     */
    public void setTimeSyncProt(TTimeSyncProt value) {
        this.timeSyncProt = value;
    }

    /**
     * Gets the value of the commProt property.
     * 
     * @return
     *     possible object is
     *     {@link TCommProt }
     *     
     */
    public TCommProt getCommProt() {
        return commProt;
    }

    /**
     * Sets the value of the commProt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCommProt }
     *     
     */
    public void setCommProt(TCommProt value) {
        this.commProt = value;
    }

    /**
     * Gets the value of the nameLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameLength() {
        if (nameLength == null) {
            return "32";
        } else {
            return nameLength;
        }
    }

    /**
     * Sets the value of the nameLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameLength(String value) {
        this.nameLength = value;
    }

}
