//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for tServiceConfReportControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tServiceConfReportControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceWithMax">
 *       &lt;attribute name="bufMode" default="both">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *             &lt;enumeration value="unbuffered"/>
 *             &lt;enumeration value="buffered"/>
 *             &lt;enumeration value="both"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="bufConf" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="maxBuf" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tServiceConfReportControl")
public class TServiceConfReportControl
    extends TServiceWithMax
{

    @XmlAttribute(name = "bufMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bufMode;
    @XmlAttribute(name = "bufConf")
    protected Boolean bufConf;
    @XmlAttribute(name = "maxBuf")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxBuf;

    /**
     * Gets the value of the bufMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBufMode() {
        if (bufMode == null) {
            return "both";
        } else {
            return bufMode;
        }
    }

    /**
     * Sets the value of the bufMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBufMode(String value) {
        this.bufMode = value;
    }

    /**
     * Gets the value of the bufConf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBufConf() {
        if (bufConf == null) {
            return false;
        } else {
            return bufConf;
        }
    }

    /**
     * Sets the value of the bufConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBufConf(Boolean value) {
        this.bufConf = value;
    }

    /**
     * Gets the value of the maxBuf property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxBuf() {
        return maxBuf;
    }

    /**
     * Sets the value of the maxBuf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxBuf(Long value) {
        this.maxBuf = value;
    }

}
