//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSettingControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSettingControl">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tUnNaming">
 *       &lt;attribute name="numOfSGs" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="actSG" default="1">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *             &lt;minInclusive value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="resvTms" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSettingControl")
public class TSettingControl
    extends TUnNaming
{

    @XmlAttribute(name = "numOfSGs", required = true)
    protected long numOfSGs;
    @XmlAttribute(name = "actSG")
    protected Long actSG;
    @XmlAttribute(name = "resvTms")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer resvTms;

    /**
     * Gets the value of the numOfSGs property.
     * 
     */
    public long getNumOfSGs() {
        return numOfSGs;
    }

    /**
     * Sets the value of the numOfSGs property.
     * 
     */
    public void setNumOfSGs(long value) {
        this.numOfSGs = value;
    }

    /**
     * Gets the value of the actSG property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getActSG() {
        if (actSG == null) {
            return  1L;
        } else {
            return actSG;
        }
    }

    /**
     * Sets the value of the actSG property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setActSG(Long value) {
        this.actSG = value;
    }

    /**
     * Gets the value of the resvTms property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResvTms() {
        return resvTms;
    }

    /**
     * Sets the value of the resvTms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResvTms(Integer value) {
        this.resvTms = value;
    }

}
