//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSettingGroups complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSettingGroups">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="SGEdit" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo">
 *                 &lt;attribute name="resvTms" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ConfSG" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo">
 *                 &lt;attribute name="resvTms" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSettingGroups", propOrder = {

})
public class TSettingGroups {

    @XmlElement(name = "SGEdit")
    protected TSettingGroups.SGEdit sgEdit;
    @XmlElement(name = "ConfSG")
    protected TSettingGroups.ConfSG confSG;

    /**
     * Gets the value of the sgEdit property.
     * 
     * @return
     *     possible object is
     *     {@link TSettingGroups.SGEdit }
     *     
     */
    public TSettingGroups.SGEdit getSGEdit() {
        return sgEdit;
    }

    /**
     * Sets the value of the sgEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSettingGroups.SGEdit }
     *     
     */
    public void setSGEdit(TSettingGroups.SGEdit value) {
        this.sgEdit = value;
    }

    /**
     * Gets the value of the confSG property.
     * 
     * @return
     *     possible object is
     *     {@link TSettingGroups.ConfSG }
     *     
     */
    public TSettingGroups.ConfSG getConfSG() {
        return confSG;
    }

    /**
     * Sets the value of the confSG property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSettingGroups.ConfSG }
     *     
     */
    public void setConfSG(TSettingGroups.ConfSG value) {
        this.confSG = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo">
     *       &lt;attribute name="resvTms" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ConfSG
        extends TServiceYesNo
    {

        @XmlAttribute(name = "resvTms")
        protected Boolean resvTms;

        /**
         * Gets the value of the resvTms property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isResvTms() {
            if (resvTms == null) {
                return false;
            } else {
                return resvTms;
            }
        }

        /**
         * Sets the value of the resvTms property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setResvTms(Boolean value) {
            this.resvTms = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo">
     *       &lt;attribute name="resvTms" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SGEdit
        extends TServiceYesNo
    {

        @XmlAttribute(name = "resvTms")
        protected Boolean resvTms;

        /**
         * Gets the value of the resvTms property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isResvTms() {
            if (resvTms == null) {
                return false;
            } else {
                return resvTms;
            }
        }

        /**
         * Sets the value of the resvTms property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setResvTms(Boolean value) {
            this.resvTms = value;
        }

    }

}
