//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSMVSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSMVSettings">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceSettings">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="SmpRate">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                 &lt;minExclusive value="0"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="SamplesPerSec">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                 &lt;minExclusive value="0"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="SecPerSamples">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt">
 *                 &lt;minExclusive value="0"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="McSecurity" type="{http://www.iec.ch/61850/2003/SCL}tMcSecurity" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="svID" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="optFields" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="smpRate" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsEnum" default="Fix" />
 *       &lt;attribute name="samplesPerSec" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="pdcTimeStamp" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="synchSrcId" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="nofASDU" type="{http://www.iec.ch/61850/2003/SCL}tServiceSettingsNoDynEnum" default="Fix" />
 *       &lt;attribute name="kdaParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSMVSettings", propOrder = {
    "smpRateOrSamplesPerSecOrSecPerSamples",
    "mcSecurity"
})
public class TSMVSettings
    extends TServiceSettings
{

    @XmlElementRefs({
        @XmlElementRef(name = "SmpRate", namespace = "http://www.iec.ch/61850/2003/SCL", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SamplesPerSec", namespace = "http://www.iec.ch/61850/2003/SCL", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "SecPerSamples", namespace = "http://www.iec.ch/61850/2003/SCL", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<Long>> smpRateOrSamplesPerSecOrSecPerSamples;
    @XmlElement(name = "McSecurity")
    protected TMcSecurity mcSecurity;
    @XmlAttribute(name = "svID")
    protected TServiceSettingsEnum svID;
    @XmlAttribute(name = "optFields")
    protected TServiceSettingsEnum optFields;
    @XmlAttribute(name = "smpRate")
    protected TServiceSettingsEnum smpRate;
    @XmlAttribute(name = "samplesPerSec")
    protected Boolean samplesPerSec;
    @XmlAttribute(name = "pdcTimeStamp")
    protected Boolean pdcTimeStamp;
    @XmlAttribute(name = "synchSrcId")
    protected Boolean synchSrcId;
    @XmlAttribute(name = "nofASDU")
    protected TServiceSettingsNoDynEnum nofASDU;
    @XmlAttribute(name = "kdaParticipant")
    protected Boolean kdaParticipant;

    /**
     * Gets the value of the smpRateOrSamplesPerSecOrSecPerSamples property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the smpRateOrSamplesPerSecOrSecPerSamples property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSmpRateOrSamplesPerSecOrSecPerSamples().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Long>> getSmpRateOrSamplesPerSecOrSecPerSamples() {
        if (smpRateOrSamplesPerSecOrSecPerSamples == null) {
            smpRateOrSamplesPerSecOrSecPerSamples = new ArrayList<JAXBElement<Long>>();
        }
        return this.smpRateOrSamplesPerSecOrSecPerSamples;
    }

    /**
     * Gets the value of the mcSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link TMcSecurity }
     *     
     */
    public TMcSecurity getMcSecurity() {
        return mcSecurity;
    }

    /**
     * Sets the value of the mcSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMcSecurity }
     *     
     */
    public void setMcSecurity(TMcSecurity value) {
        this.mcSecurity = value;
    }

    /**
     * Gets the value of the svID property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getSvID() {
        if (svID == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return svID;
        }
    }

    /**
     * Sets the value of the svID property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setSvID(TServiceSettingsEnum value) {
        this.svID = value;
    }

    /**
     * Gets the value of the optFields property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getOptFields() {
        if (optFields == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return optFields;
        }
    }

    /**
     * Sets the value of the optFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setOptFields(TServiceSettingsEnum value) {
        this.optFields = value;
    }

    /**
     * Gets the value of the smpRate property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public TServiceSettingsEnum getSmpRate() {
        if (smpRate == null) {
            return TServiceSettingsEnum.FIX;
        } else {
            return smpRate;
        }
    }

    /**
     * Sets the value of the smpRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsEnum }
     *     
     */
    public void setSmpRate(TServiceSettingsEnum value) {
        this.smpRate = value;
    }

    /**
     * Gets the value of the samplesPerSec property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSamplesPerSec() {
        if (samplesPerSec == null) {
            return false;
        } else {
            return samplesPerSec;
        }
    }

    /**
     * Sets the value of the samplesPerSec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSamplesPerSec(Boolean value) {
        this.samplesPerSec = value;
    }

    /**
     * Gets the value of the pdcTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPdcTimeStamp() {
        if (pdcTimeStamp == null) {
            return false;
        } else {
            return pdcTimeStamp;
        }
    }

    /**
     * Sets the value of the pdcTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPdcTimeStamp(Boolean value) {
        this.pdcTimeStamp = value;
    }

    /**
     * Gets the value of the synchSrcId property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSynchSrcId() {
        if (synchSrcId == null) {
            return false;
        } else {
            return synchSrcId;
        }
    }

    /**
     * Sets the value of the synchSrcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchSrcId(Boolean value) {
        this.synchSrcId = value;
    }

    /**
     * Gets the value of the nofASDU property.
     * 
     * @return
     *     possible object is
     *     {@link TServiceSettingsNoDynEnum }
     *     
     */
    public TServiceSettingsNoDynEnum getNofASDU() {
        if (nofASDU == null) {
            return TServiceSettingsNoDynEnum.FIX;
        } else {
            return nofASDU;
        }
    }

    /**
     * Sets the value of the nofASDU property.
     * 
     * @param value
     *     allowed object is
     *     {@link TServiceSettingsNoDynEnum }
     *     
     */
    public void setNofASDU(TServiceSettingsNoDynEnum value) {
        this.nofASDU = value;
    }

    /**
     * Gets the value of the kdaParticipant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isKdaParticipant() {
        if (kdaParticipant == null) {
            return false;
        } else {
            return kdaParticipant;
        }
    }

    /**
     * Sets the value of the kdaParticipant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKdaParticipant(Boolean value) {
        this.kdaParticipant = value;
    }

}
