//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSMVsc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSMVsc">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceWithMax">
 *       &lt;attribute name="delivery" type="{http://www.iec.ch/61850/2003/SCL}tSMVDeliveryEnum" default="multicast" />
 *       &lt;attribute name="deliveryConf" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="sv" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="rSV" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSMVsc")
public class TSMVsc
    extends TServiceWithMax
{

    @XmlAttribute(name = "delivery")
    protected TSMVDeliveryEnum delivery;
    @XmlAttribute(name = "deliveryConf")
    protected Boolean deliveryConf;
    @XmlAttribute(name = "sv")
    protected Boolean sv;
    @XmlAttribute(name = "rSV")
    protected Boolean rsv;

    /**
     * Gets the value of the delivery property.
     * 
     * @return
     *     possible object is
     *     {@link TSMVDeliveryEnum }
     *     
     */
    public TSMVDeliveryEnum getDelivery() {
        if (delivery == null) {
            return TSMVDeliveryEnum.MULTICAST;
        } else {
            return delivery;
        }
    }

    /**
     * Sets the value of the delivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSMVDeliveryEnum }
     *     
     */
    public void setDelivery(TSMVDeliveryEnum value) {
        this.delivery = value;
    }

    /**
     * Gets the value of the deliveryConf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDeliveryConf() {
        if (deliveryConf == null) {
            return false;
        } else {
            return deliveryConf;
        }
    }

    /**
     * Sets the value of the deliveryConf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeliveryConf(Boolean value) {
        this.deliveryConf = value;
    }

    /**
     * Gets the value of the sv property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSv() {
        if (sv == null) {
            return true;
        } else {
            return sv;
        }
    }

    /**
     * Sets the value of the sv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSv(Boolean value) {
        this.sv = value;
    }

    /**
     * Gets the value of the rsv property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRSV() {
        if (rsv == null) {
            return false;
        } else {
            return rsv;
        }
    }

    /**
     * Sets the value of the rsv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRSV(Boolean value) {
        this.rsv = value;
    }

}
