//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSupSubscription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSupSubscription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="maxGo" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="maxSv" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSupSubscription")
public class TSupSubscription {

    @XmlAttribute(name = "maxGo", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long maxGo;
    @XmlAttribute(name = "maxSv", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long maxSv;

    /**
     * Gets the value of the maxGo property.
     * 
     */
    public long getMaxGo() {
        return maxGo;
    }

    /**
     * Sets the value of the maxGo property.
     * 
     */
    public void setMaxGo(long value) {
        this.maxGo = value;
    }

    /**
     * Gets the value of the maxSv property.
     * 
     */
    public long getMaxSv() {
        return maxSv;
    }

    /**
     * Sets the value of the maxSv property.
     * 
     */
    public void setMaxSv(long value) {
        this.maxSv = value;
    }

}
