//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSystemLNGroupEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tSystemLNGroupEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name">
 *     &lt;length value="4"/>
 *     &lt;pattern value="L[A-Z]*"/>
 *     &lt;pattern value="LLN0"/>
 *     &lt;enumeration value="LLN0"/>
 *     &lt;enumeration value="LPHD"/>
 *     &lt;enumeration value="LCCH"/>
 *     &lt;enumeration value="LGOS"/>
 *     &lt;enumeration value="LSVS"/>
 *     &lt;enumeration value="LTIM"/>
 *     &lt;enumeration value="LTMS"/>
 *     &lt;enumeration value="LTRK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tSystemLNGroupEnum")
@XmlEnum
public enum TSystemLNGroupEnum {

    @XmlEnumValue("LLN0")
    LLN_0("LLN0"),
    LPHD("LPHD"),
    LCCH("LCCH"),
    LGOS("LGOS"),
    LSVS("LSVS"),
    LTIM("LTIM"),
    LTMS("LTMS"),
    LTRK("LTRK");
    private final String value;

    TSystemLNGroupEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TSystemLNGroupEnum fromValue(String v) {
        for (TSystemLNGroupEnum c: TSystemLNGroupEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
