//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTimeSyncProt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTimeSyncProt">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tServiceYesNo">
 *       &lt;attribute name="sntp" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="iec61850_9_3" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="c37_238" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="other" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTimeSyncProt")
public class TTimeSyncProt
    extends TServiceYesNo
{

    @XmlAttribute(name = "sntp")
    protected Boolean sntp;
    @XmlAttribute(name = "iec61850_9_3")
    protected Boolean iec6185093;
    @XmlAttribute(name = "c37_238")
    protected Boolean c37238;
    @XmlAttribute(name = "other")
    protected Boolean other;

    /**
     * Gets the value of the sntp property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSntp() {
        if (sntp == null) {
            return true;
        } else {
            return sntp;
        }
    }

    /**
     * Sets the value of the sntp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSntp(Boolean value) {
        this.sntp = value;
    }

    /**
     * Gets the value of the iec6185093 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIec6185093() {
        if (iec6185093 == null) {
            return false;
        } else {
            return iec6185093;
        }
    }

    /**
     * Sets the value of the iec6185093 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIec6185093(Boolean value) {
        this.iec6185093 = value;
    }

    /**
     * Gets the value of the c37238 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isC37238() {
        if (c37238 == null) {
            return false;
        } else {
            return c37238;
        }
    }

    /**
     * Sets the value of the c37238 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setC37238(Boolean value) {
        this.c37238 = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOther() {
        if (other == null) {
            return false;
        } else {
            return other;
        }
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOther(Boolean value) {
        this.other = value;
    }

}
