//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 06:34:15 PM MSK 
//


package ru.nti.dpts.schememanagerback.service.converter.scl2007B4;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tVoltageLevel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tVoltageLevel">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iec.ch/61850/2003/SCL}tEquipmentContainer">
 *       &lt;sequence>
 *         &lt;element name="Voltage" type="{http://www.iec.ch/61850/2003/SCL}tVoltage" minOccurs="0"/>
 *         &lt;element name="Bay" type="{http://www.iec.ch/61850/2003/SCL}tBay" maxOccurs="unbounded"/>
 *         &lt;element name="Function" type="{http://www.iec.ch/61850/2003/SCL}tFunction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="nomFreq">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="numPhases">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *             &lt;minExclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tVoltageLevel", propOrder = {
    "voltage",
    "bay",
    "function"
})
public class TVoltageLevel
    extends TEquipmentContainer
{

    @XmlElement(name = "Voltage")
    protected TVoltage voltage;
    @XmlElement(name = "Bay", required = true)
    protected List<TBay> bay;
    @XmlElement(name = "Function")
    protected List<TFunction> function;
    @XmlAttribute(name = "nomFreq")
    protected BigDecimal nomFreq;
    @XmlAttribute(name = "numPhases")
    protected Short numPhases;

    /**
     * Gets the value of the voltage property.
     * 
     * @return
     *     possible object is
     *     {@link TVoltage }
     *     
     */
    public TVoltage getVoltage() {
        return voltage;
    }

    /**
     * Sets the value of the voltage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVoltage }
     *     
     */
    public void setVoltage(TVoltage value) {
        this.voltage = value;
    }

    /**
     * Gets the value of the bay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TBay }
     * 
     * 
     */
    public List<TBay> getBay() {
        if (bay == null) {
            bay = new ArrayList<TBay>();
        }
        return this.bay;
    }

    /**
     * Gets the value of the function property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the function property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFunction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TFunction }
     * 
     * 
     */
    public List<TFunction> getFunction() {
        if (function == null) {
            function = new ArrayList<TFunction>();
        }
        return this.function;
    }

    /**
     * Gets the value of the nomFreq property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNomFreq() {
        return nomFreq;
    }

    /**
     * Sets the value of the nomFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNomFreq(BigDecimal value) {
        this.nomFreq = value;
    }

    /**
     * Gets the value of the numPhases property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getNumPhases() {
        return numPhases;
    }

    /**
     * Sets the value of the numPhases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setNumPhases(Short value) {
        this.numPhases = value;
    }

}
